title: "Francisco Ossian"
categories:
  - "Tecnologia"
  - "Desenvolvimento Web"
description: "Francisco Ossian, desenvolvedor fullstack. (js, python, C++, C)"
keywords: "Francisco Ossian, Tecnologia, Desenvolvimento Web, Artigos, Posts"

OG:
  title: "Francisco Ossian"
  description: "Francisco Ossian, desenvolvedor fullstack. (js, python, C++, C)"
  url: "https://www.foln.dev"
  type: "website"
  keywords: "Francisco Ossian, Tecnologia, Desenvolvimento Web, Artigos, Posts"

#--------------------------------------------------------------------------------       
#-------------------------------â˜ï¸ SEO  -----------------------------------------
# -------------------------------------------------------------------------------
#-------------------------------ðŸ‘‡ Content --------------------------------------
#--------------------------------------------------------------------------------

about:
  title: OlÃ¡ ðŸ‘‹
  text: >
    Me chamo Francisco Ossian,
    sou um profissional da tecnologia apaixonado por transformar ideias em realidade.
    Com criatividade, determinaÃ§Ã£o e habilidades tÃ©cnicas,
    estou sempre pronto para novos desafios.
    Vamos trabalhar juntos para tornar seu projeto uma realidade?

what_i_do:
  title: O QUE EU FAÃ‡O
  text: >
    Transformo conceitos em soluÃ§Ãµes digitais.
    Desde o desenvolvimento de sites responsivos atÃ© a criaÃ§Ã£o de aplicativos mÃ³veis intuitivos,
    estou aqui para alcanÃ§ar seus objetivos.
    Com expertise em tecnologias como React.js, React Native, Python e muito mais.
  link: https://api.whatsapp.com/send/?phone=558592048568&text&type=phone_number&app_absent=0

projects:
  - title: Chalk
    description: >
      Desenvolvimento e lanÃ§amento de uma rede social para conectar pessoas,
      com foco em novos amigos, parceiros e grupos.
      O aplicativo possui um sistema de "match" customizado,
      proporcionando uma experiÃªncia Ãºnica.
    shortDescription: Aplicativo
    media: https://media.starlightcms.io/workspaces/foln/folndev/original/chalk-icon-gEQKlyu9TE.png
    videoUrl: ''
    link: https://play.google.com/store/apps/details?id=com.foln.chalk
    tags: ['React Native', Expo, Firebase, I18N, 'Socket.io', '']
    type: 'Rede social'
  - title: Code Slide
    type: Ferramenta
    media: https://firebasestorage.googleapis.com/v0/b/foln-dev.appspot.com/o/1.png?alt=media&token=651daebc-e8cb-4075-8c05-96c93f8b491a
    shortDescription: Criador de Slides a partir de Markdonw, usando Marp como backend e foi criado um site simples e intuitÃ­vo para codificar slides.
    videoUrl: https://firebasestorage.googleapis.com/v0/b/foln-dev.appspot.com/o/screen-20240725-095416.mp4?alt=media&token=eac158c8-82af-4d2b-afb6-dc38d8b78226
    description: Criador de Slides a partir de Markdonw. Escreva slides usando markdown, compile e compartilhe com amigos usando p2p. Powered by Markdown Presentation Ecosystem
    tags: [markdonw-slides, slide-generator, markdonw, Next.js, next.js]
    link: https://codeslide.foln.dev/
  - title: Blog
    type: site
    shortDescription: Blog com CMS
    videoUrl: ''
    description: Meu blog pessoal (dentro desse site) que uso para postar coisas da Ã¡rea.
    tags: [blog, react.js, next.js, CMS, githubAPI, graphQL]
    media: https://media.starlightcms.io/workspaces/foln/folndev/original/chalk-icon-gEQKlyu9TE.png
    link: https://www.foln.dev/blog
  - title: Site do ISGH â€¢ Em equipe
    type: Site institucional
    shortDescription: Site institucional do ISGH
    videoUrl: https://firebasestorage.googleapis.com/v0/b/foln-dev.appspot.com/o/screen-20240725-095002~2.mp4?alt=media&token=5e8eff78-4b89-458f-9fcb-4ae51ead27a4
    media: https://firebasestorage.googleapis.com/v0/b/foln-dev.appspot.com/o/unnamed.jpg?alt=media&token=cd395f22-84fd-4eff-8667-71321091868d
    description: >
      Desenvolvido junto com a equipa da Advance, de qual fiz
      parte da equipe de desenvolvimento web. Tive tutoria de um desenvolvedor sÃªnior
      em cada etapa
    tags: [react.js, next.js]
    link: https://www.isgh.org.br/
